name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    name: Label the pull request
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  notify-videojuegos:
    needs: triage
    runs-on: ubuntu-latest
    name: send discord message to videojuegos
    steps:
    - name: Check if pull request has label "videojuegos"
      if: |
        contains(github.event.pull_request.labels.*.name, 'videojuegos')
      run: |
        curl -s -X POST "${{ secrets.DISCORD_VIDEOJUEGOS }}" -d "content= ¡Hay un nuevo pull request en Github! NOMBRE: \" ${{github.event.pull_request.title}} \" Creado por: ${{github.event.pull_request.user.login}} \n  ${{github.event.pull_request.html_url}}"
        
  notify-principiantes-web:
    needs: triage
    runs-on: ubuntu-latest
    name: send discord message to principiantes web
    steps:
    - name: Check if pull request has label "principiantes-web"
      if: |
        contains(github.event.pull_request.labels.*.name, 'principiantes-web')
        
      run: |
        curl -s -X POST "${{ secrets.DISCORD_PRINCIPIANTES_WEB }}" -d "content= ¡Hay un nuevo pull request en Github! NOMBRE: \" ${{github.event.pull_request.title}} \" Creado por: \" ${{github.event.pull_request.user.login}} \"  ${{github.event.pull_request.html_url}}"
  
  notify-avanzados-web:
    needs: triage
    runs-on: ubuntu-latest
    name: send discord message to avanzados web
    steps:   
    - name: Check if pull request has label "avanzados-web"
      if: |
        contains(github.event.pull_request.labels.*.name, 'avanzados-web')
        
      run: |
        curl -s -X POST "${{ secrets.DISCORD_AVANZADOS_WEB }}" -d "content= ¡Hay un nuevo pull request en Github! NOMBRE: \" ${{github.event.pull_request.title}} \" Creado por: \" ${{github.event.pull_request.user.login}} \"  ${{github.event.pull_request.html_url}}"
      
